### ISSUE TITLE
(Easy) Update mongodb-driver-sync to v4.1.0 to allow srv+mongodb:// URL scheme to work on Windows

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-mongodb-plugin#3]

**Comment by gaurav9822** [comment]
@rishabhpoddar Can I take this one?

**Comment by rishabhpoddar** [comment]
Hey @gaurav9822. Sure!!

The current version of this lib that's being used has a bug which prevents `srv+mongodb` from working on Windows. It would be very helpful if you could test it on windows after you have changed the [build.gradle](https://github.com/supertokens/supertokens-mongodb-plugin/blob/master/build.gradle) and the [implementationDependencies.json](https://github.com/supertokens/supertokens-mongodb-plugin/blob/master/implementationDependencies.json) files.

Thanks.

**Comment by gaurav9822** [comment]
Unable to import project in intellij -

> Build file 'D:\tempProjects\java\supertokens-mongodb-plugin\build.gradle' line: 13
> 
> A problem occurred evaluating root project 'supertokens-mongodb-plugin'.
> > Project with path ':supertokens-plugin-interface' could not be found in root project 'supertokens-mongodb-plugin'.

**Comment by rishabhpoddar** [comment]
Hi @gaurav9822, please make sure you setup the project properly using [this contributing.md](https://github.com/supertokens/supertokens-core/blob/master/CONTRIBUTING.md) file first :)

You can join [our discord](https://supertokens.io/discord) if you need more help setting it up.

**Comment by rishabhpoddar** [comment]
@gaurav9822 , are you still working on this issue? If yes, I will reassign it to you.

**Comment by rishabhpoddar** [comment]
srv+mongodb:// are supported now.
